# image will be published to ghcr.io/<user>/<name>
name: yboxproworkstation
# description will be included in the image's metadata
description: devbox they way i want it set.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP
#base-image: ghcr.io/aguslr/bluefusion
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
             # put configuration files you want in /etc/ on a booted system 
      #- etc: /etc

      - distroboxhome: /distroboxhome
      # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
  - type: brew
    option: true
  - type: gnome-extensions
    install: 
    - 2986 #runcat
    - 6682 #astra
    - 5940 #quick audio settings
    - 3193 # blur my shell
  - type: script
    scripts:
    #- distrobox.sh
    #- extra-packages.sh
    - gnomextra.sh
    #snippets: 
   #- "curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install ostree --no-confirm --persistence=/var/lib/nix"
   # scripts: 
   #- extra-packages.sh
   #- distrobox.sh
  #- type: gschema-overrides
   # include:
   # - org.gnome.shell/
   type: yafti 
  option: true
    
